version: '3.7'
services:
    nodejs:
        image: 'node:14.15.0-alpine3.12'
        working_dir: /home/node/app
        container_name: front
        command:
            - /bin/sh
            - '-c'
            - 'npm install && npm run serve'
        volumes:
            - './:/home/node/app:rw'
        ports:
            - '80:8080'
        networks:
            - TestVue-CLI
        environment:
            HOST: 0.0.0.0
volumes: {}
networks: { TestVue-CLI: {} }
